### ISSUE TITLE
Remove unused proposal requirements

### ISSUE THREAD

**Issue by vmbrasseur** [SeaGL/osem#13]
Every year we field a lot of questions about this stuff:

<img width="213" alt="screen shot 2018-03-17 at 20 25 32" src="https://user-images.githubusercontent.com/298927/37562267-8a911760-2a21-11e8-9bd3-f4d71f2c7a87.png">

We don't use most of the things which OSEM sees as "requirements":

<img width="446" alt="screen shot 2018-03-17 at 20 26 07" src="https://user-images.githubusercontent.com/298927/37562281-b2ec3abe-2a21-11e8-9351-eaa69f000562.png">

Perfect world? Everything on that "Your todo list" is a toggle-able option in CFP setup. But we don't live in a perfect world, so…

Things we absolutely want to remove from the process entirely:

* Add a subtitle
* Add a commercial
* Speakers(s) not registered to the conference (since we don't require registration from anyone)

Anything else we get is just a bonus.

**Comment by emanuil-tolev** [comment]
Hi there. Happy to help out. These conf systems tend to have a *lot* of context knowledge baked into them, so there will be some domain rampup time before I can make sensible fixes. I've worked *with* pentabarf (XML outputs) but not *on* penta or OSEM. 

I'll evaluate how much of a proper fix I can do or outline a temporary workaround by 15 May. Then hopefully get it in the following 10 days.

**Comment by vmbrasseur** [comment]
@kormoc? Could you oblige?

**Comment by kormoc** [comment]
Everything that we have setup with the exception of the database passwords should be in the repo. We have the deployment information in wiki and https://github.com/SeaGL/osem/blob/master/config/deploy.rb contains the code

**Comment by emanuil-tolev** [comment]
> Perfect world? Everything on that "Your todo list" is a toggle-able option in CFP setup.

OK, I think I've managed to achieve that in PR #14 . You can toggle any of the options at any time by editing the CFP and it just affects what's shown in the speaker todo list.

**Comment by AndrewKvalheim** [comment]
- Local resolution: #14
- Upstream issue: openSUSE/osem#1544
