### ISSUE TITLE
No email confirmation for talk submissions

### ISSUE THREAD

**Issue by vmbrasseur** [SeaGL/osem#18]
During the 2018 CFP we had several people confused and asking whether we'd actually received their proposals. They didn't receive any email confirmations at all.

It's a reasonable expectation that the system would send the submitter a confirmation.

As far as I can tell, this functionality isn't included in OSEM at all…?

It would be nice to add it before 2019.

The email should at a minimum be:

> TO: $account_email
> FROM: $admin_email
> SUBJECT: $conference has received your proposal: $title
> BODY: 
> Thank you for proposing a talk to $conference.
> 
> We've received your proposal, "$title".
>
> To make any changes to your proposal, please click this link:
> $link_to_proposal

In a perfect world both the subject and the body would be configurable somehow, maybe in the same interface that allows us to configure the accept/reject emails.

**Comment by AndrewKvalheim** [comment]
Completed upstream with openSUSE/osem#2094
