### ISSUE TITLE
 No notification when a confirmed talk is withdrawn

### ISSUE THREAD

**Issue by vmbrasseur** [SeaGL/osem#21]
I had this problem last year as well and just hit it for 2018.

Speakers are withdrawing talks after they've been accepted and understandably expect that I'll know that. Except I don't. There are no notifications to organisers when someone withdraws a talk.

This is proving very inconvenient. I just spent several minutes trying to find a talk to schedule but it no longer existed (from a scheduling POV). Last year some people withdrew talks after they were scheduled but I had no notification so I didn't know until the last minute that there were now holes in the schedule.

Notification is necessary when an accepted talk withdraws.

**Comment by AndrewKvalheim** [comment]
Addressed upstream with openSUSE/osem#1805
