### ISSUE TITLE
Missing community benefits by being far behind master branch

### ISSUE THREAD

**Issue by bear454** [SeaGL/osem#22]
Hi all,

Congrats on a successful SeaGL! After you all take a short break, I'd like to work with you on getting your osem instance caught up with the master branch, so we can work together on features & fixes. Osem upstream has made a lot of improvements, and you have some features that would make great additions upstream - but they'll need to be forward ported. Additionally, I'd like to get at least one of you on the maintainers list, so we have some more active admins doing continuous upstream maintenance (maintainers upstream seem to come & go based on when _their_ conference needs improvements).

I have a window to collaborate on this until the end of January, 2019... after that LNFW2019 will be in full swing, and I won't be able to work on this... so let's rock & roll!

**Comment by altsalt** [comment]
Digging through some old emails and super glad you added this!

Hopefully you've connected with @kormoc and there is some forward momentum!

**Comment by bear454** [comment]
I haven't! Hi @kormoc. I'd love to have a chat/call/etc. and see how we can move forward. I _desperately_ need another upstream committer, to maintain our review policy.

**Comment by altsalt** [comment]
Thanks again for opening this issue @bear454 !

As February has started, I'll wish you luck with LFNW and attempt to find someone who can own this when your time again becomes available.

**Comment by bear454** [comment]
Upstream, _osem_ is working on closing bugs & stabilizing feature changes for a v2 release... this would be a good point for merging on, and then working on upstreaming features from there.

https://github.com/openSUSE/osem/projects/5

**Comment by AndrewKvalheim** [comment]
Working on a path to upstream at [`AndrewKvalheim:trial`](https://github.com/AndrewKvalheim/osem/tree/trial).
