### ISSUE TITLE
Add Pacific Northwest checkbox to CfP form

### ISSUE THREAD

**Issue by altsalt** [SeaGL/osem#23]
Should be simple enough to follow the same pattern as the other additions... should be.

**Comment by altsalt** [comment]
Think you can take a look at this by Friday so it can go out with the CfP @AndrewKvalheim ?

**Comment by AndrewKvalheim** [comment]
By tomorrow? Maybe. I'll take a look this evening.

**Comment by AndrewKvalheim** [comment]
So what are we looking for? Something like this? I don't have any context for what information this is intended to collect.

<img src="https://user-images.githubusercontent.com/1844746/87113171-7e306980-c222-11ea-9288-af9d45a921da.png" alt="☐ Pacific Northwest" width="596" />

**Comment by altsalt** [comment]
Yeah, just like that, but let's go with this text for now... it can be modified after I would assume.

"I am local to the Pacific Northwest"
