### ISSUE TITLE
Add diversity checkbox to proposal form

### ISSUE THREAD

**Issue by vmbrasseur** [SeaGL/osem#7]
Work started on this in #4 

We would like to get a checkbox on the talk proposal form for tracking diversity. The phrasing we chose last year is, "identify as a member of a group that is historically under-represented in technology". That still works well.

The UI should be a simple toggle (checkbox, etc). It should not be required for submitting a proposal.

**Comment by emanuil-tolev** [comment]
Oh. This is probably more important and easier than #13, I didn't see it.

To clarify, I can see 2 relevant ways to position this question. They're different enough to make a significant diff to the meaning. Which one (or 3rd option) would you go for?

![untitled](https://user-images.githubusercontent.com/1190172/40463032-b3537a80-5f0a-11e8-9da8-f5535065c302.png)

or 

![untitled](https://user-images.githubusercontent.com/1190172/40463186-a13cff64-5f0b-11e8-8ae2-01c78b865fdb.png)

**Comment by emanuil-tolev** [comment]
This seems to have been completed. Anything else to do here, maybe add the ability to edit this info after initially creating the proposal?

**Comment by vmbrasseur** [comment]
Not actually completed, as the checkboxes never actually worked. :-(

**Comment by futureperfect** [comment]
@vmbrasseur I pushed my WIP branch as #15 as a conversation starter. It looks like that gets it most of the way to collecting and surfacing diversity stats, but I'm not confident enough without the entire test suite.

It looks like some work was already done to add diversity pie charts to the conference dashboard that my changes enabled.

<img width="988" alt="screen shot 2018-05-23 at 10 36 13 pm" src="https://user-images.githubusercontent.com/4185/40468208-94745b6c-5ee1-11e8-8f1d-b72da42779b2.png">
